language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories:
   - /home/travis/.rvm/
   - /home/travis/bundle
env:
 # Production like setup
 - SECRET_TOKEN=e815982094c62436066bafc9151f2d33c4a351a776654cb7487476de260a4592
   MQTT_HOST=example.com
   OS_UPDATE_SERVER=http://example.com
   FW_UPDATE_SERVER=http://example.com
   DB=postgresql
   COVERALLS_REPO_TOKEN=lEX6nkql7y2YFCcIXVq5ORvdvMtYzfZdG
 # Self hosted like setup
 - SECRET_TOKEN=e815982094c62436066bafc9151f2d33c4a351a776654cb7487476de260a4592
   MQTT_HOST=127.0.0.1
   OS_UPDATE_SERVER=http://example.com
   FW_UPDATE_SERVER=http://example.com
   DB=postgresql
   COVERALLS_REPO_TOKEN=lEX6nkql7y2YFCcIXVq5ORvdvMtYzfZdG
   API_HOST=127.0.0.1
   NO_EMAILS=TRUE
before_install:
  - rvm install 2.5.1
  - rvm use 2.5.1
install:
  - yarn install
  - bundle install --jobs=3 --retry=3 --path=/home/travis/bundle
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
script:
- bundle exec rspec --fail-fast=3
- npm run typecheck
- npm run test-slow
- npm run coverage
