# ░██████░░███████░░█████░░░██████░░
# ░██░░░░░░░░██░░░░██░░░██░░██░░░██░  READ THIS BEFORE USING IT.
# ░██████░░░░██░░░░██░░░██░░██████░░  SEE NOTES BELOW:
# ░░░░░██░░░░██░░░░██░░░██░░██░░░░░░
# ░██████░░░░██░░░░░████░░░░██░░░░░░
# You will hit issues if any of these are set to the wrong value.
# Please read each line of this file before starting the server.
#
#  PLEASE READ ALL ENTRIES.
# =============================================================================
#
# Self hosting users can safely delete this (a new key will be created).
# This key is used to exchange secrets between bots and MQTT servers (important
# if you don't use SSL)
# SERVER WONT WORK IF YOU FORGET TO DELETE THIS EXAMPLE TEXT BELOW.
# ADD A REAL RSA_KEY OR DELETE THIS LINE!!
RSA_KEY: "Change this! Keys look like `-----BEGIN RSA .........`"
# If you use Let's Encrypt for SSL,
# you must set this when renewing SSL.
# Otherwise, not required and CAN BE REMOVED.
ACME_SECRET: "-----"
# If your server is on a domain (eg: my-own-farmbot.com), put it here.
# DONT USE `localhost`.
# DONT USE `127.0.0.1`.
# DONT USE `0.0.0.0`.
# Use a real ip or domain name.
API_HOST: "12.34.56.78"
# 3000 for local development. 443 is using SSL. You will need `sudo` to use PORT
# 80 on most systems.
API_PORT: "3000"
# This can be set to anything.
# Most users can just delete it.
# This is used for people writing modifications to the software, mostly.
DOCS: "Set this to any value if you want to generate API docs after running tests"
# Most users can delete this.
# Used by people who pay for managed database hosting.
DATABASE_URL: "postgres://USERNAME:PASSWORD@URL:PORT/DB_NAME"
# MUST REPLACE.
# Generate a secret by typing `rake secret` into the console.
DEVISE_SECRET: "Used for devise. Use `rake secret` to generate a new value."
# Most personal server users can delete this.
FORCE_SSL: "Remove this if not using HTTPS://"
# FarmBot OS update server. Use default if you don't have a special use case.
# Off grid servers may have issues connecting to our update URL.
OS_UPDATE_SERVER: "https://api.github.com/repos/farmbot/farmbot_os/releases/latest"
# Google Cloud Storage API Bucket for image data.
# Deleting this will save to disk.
# Most self hosting users will want to delete this.
GCS_BUCKET: "GOOGLE_CLOUD_STORAGE_BUCKET_NAME_FOR_IMAGE_FILES"
# Google Cloud Storage ID for image data.
# Deleting this will save images to disk.
# Most self hosting users will want to delete this.
GCS_ID: "GOOGLE_CLOUD_STORAGE: 'interop' id"
# Most self hosting users will want to delete this.
GCS_KEY: "GOOGLE_CLOUD_STORAGE: 'interop' key"
# Most self hosting users will want to delete this.
HEROKU_SLUG_COMMIT: "This is set by Heroku, used by Frontend to show current version."
# Where is your MQTT server running?
# Use a REAL IP ADDRESS if you are controlling real bots.
# 0.0.0.0 is only OK for software testing. Change this!
MQTT_HOST: "98.76.54.32"
# Delete this line if you are not an employee of FarmBot, Inc.
NPM_ADDON: "Used by FarmBot, Inc. to load proprietary extras, like Rollbar."
# Same as above. Can be deleted unless you are a Rollbar.IO customer.
ROLLBAR_ACCESS_TOKEN: "____"
ROLLBAR_CLIENT_TOKEN: "____"
# FarmBot, Inc. uses SendGrid to send emails.
# Delete these if you don't use send grid.
SENDGRID_PASSWORD: "Used by FarmBot, Inc"
SENDGRID_USERNAME: "Used by FarmBot, Inc"
# For email delivery. Who is your email host?
SMTP_HOST: "smtp.sendgrid.net"
# Optional with default of 587
SMTP_PORT: "587"
# Set this if you don't want to deal with email verification of new users.
# (self hosted users)
NO_EMAILS: "TRUE"
# Self hosting users can delete this line.
# If you are not using the standard MQTT broker (eg: you use a 3rd party
# MQTT vendor), you will need to change this line.
MQTT_WS: "ws://DELETE_OR_CHANGE_THIS_LINE/ws"
# ENV var used by FarmBot employees when building different versions of the JWT
# auth backend plugin.
# Can be deleted safely.
API_PUBLIC_KEY_PATH: "http://changeme.io/api/public_key"
# If you are using a shared RabbitMQ server and need to use a VHost other than
# "/", change this ENV var.
MQTT_VHOST: "/"
# If you run a server with multiple domain names (HINT: You probably don't),
# you can list the names here. This is used by FarmBot employees so that they
# can securly host the same server on multiple domain names
#     ex: my.farm.bot, my.farmbot.io
EXTRA_DOMAINS: staging.farm.bot,whatever.farm.bot
# If you are a software developer and you wish to run integration tests, set the
# ENV below to "true".
# Most users will not want this enabled.
RUN_CAPYBARA: true
# Set this to "production" in most cases.
# If you need help debugging issues, please delete this line.
RAILS_ENV: "production"
