# We use Dokku ENV configs in production, but I will leave these here for ease
# of development locally.
development:
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
test:
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
production:
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
